services:
  app:
    build: .
    image: prj-collaborate:latest
    container_name: prj-CollaboRate
    # expose:
    #   - "8501"
    volumes:
      - /home/ubuntu/docker/streamlit_collaborate/secrets.toml:/app/.streamlit/secrets.toml
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 172.22.22.101

networks:
  net:
    external: true
