@startuml
title COLLABO + RATE 액티비티 다이어그램
start
:교수는 메인 페이지를 대형 화면으로 표시;
:메인 페이지의 QR코드 메뉴를 이용하여 학생들에게 접속을 유도;
:학생들은 스마트폰으로 QR 코드를 찍고 메인 페이지 접근;
:평가할 클래스를 선택;
if (학생 OR 관리자 로그인) then (학생)
    :자신의 학번, 이름, 그룹으로 학생 페이지 접근;
    :평가할 프로젝트 세부 정보 조회;
    :평가 점수 입력;
    end
else (관리자)
    :비밀번호를 입력 하고 관리자 페이지 접근;
    :비공개(개인 장비) 혹은 공개(대형 화면)로 실시간 현황 확인;
    end
endif
@enduml