@startuml
actor 학생
actor 관리자

학생 -> "학생 페이지": 접근
"학생 페이지" -> "데이터베이스": 학생 정보 및 프로젝트 세부 정보 가져오기
"학생 페이지" -> "데이터베이스": 평가 점수 저장/업데이트


관리자 -> "관리자 페이지": 접근
"관리자 페이지" -> "데이터베이스": 학생 및 그룹 정보 가져오기
"관리자 페이지" -> "그래프 컴포넌트": 평가 점수 업데이트
"관리자 페이지" -> "데이터베이스": 데이터 초기화
"관리자 페이지" -> "시뮬레이션 컴포넌트": 평가 시뮬레이션 실행

@enduml