@startmindmap
title COLLABO + RATE 마인드맵
* 프로그램 개요
** 메인 페이지
*** 학생 로그인
*** 관리자 로그인 - 단일 관리자로 구현
*** QR 코드 및 짧은 URL 생성 및 표시
** 학생 페이지
*** 학생 정보 및 프로젝트 세부 정보 표시
*** 조 평가 점수 입력 및 업데이트
*** 같은 조원 평가 - 미구현
** 관리자 페이지
*** 실시간 평가 점수 현황 및 그래프 업데이트
*** 데이터 초기화 및 시뮬레이션 실행
*** 클래스 및 그룹 관리 - 직접 DB 수정
*** 학생 등록 - 직접 DB 수정
*** 학생 및 그룹 정보 조회 - 미구현
*** 평가 항목 관리 - 미구현
@endmindmap